apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
spec:
  type: service
  lifecycle: experimental
  owner: core-banking-team
  system: transaction-processing
