
pipeline {
  agent any

  environment {
    REGISTRY             = 'docker.io'
    BACKEND_IMAGE_NAME   = 'backend'
    FRONTEND_IMAGE_NAME  = 'frontend'
    DOCKER_CREDENTIALS_ID = 'dockerhub-creds'

    IMAGE_TAG = "${env.BUILD_NUMBER}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build & Push Backend Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS_ID,
                                         usernameVariable: 'REG_USER',
                                         passwordVariable: 'REG_PASS')]) {
          sh '''
            echo "$REG_PASS" | docker login "$REGISTRY" -u "$REG_USER" --password-stdin

            docker build -t "$REGISTRY/$BACKEND_IMAGE_NAME:$IMAGE_TAG" backend
            #docker push "$REGISTRY/$BACKEND_IMAGE_NAME:$IMAGE_TAG"
          '''
        }
      }
    }

    stage('Build & Push Frontend Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS_ID,
                                         usernameVariable: 'REG_USER',
                                         passwordVariable: 'REG_PASS')]) {
          sh '''
            echo "$REG_PASS" | docker login "$REGISTRY" -u "$REG_USER" --password-stdin

            docker build -t "$REGISTRY/$FRONTEND_IMAGE_NAME:$IMAGE_TAG" frontend
            #docker push "$REGISTRY/$FRONTEND_IMAGE_NAME:$IMAGE_TAG"
          '''
        }
      }
    }

    stage('Update Kubernetes Manifests') {
      steps {
        sh '''
          # Update backend deployment image
          sed -i '' "s|image:.*backend.*|image: docker.io/backend:$IMAGE_TAG|" backend/deploy.yaml

          # Update frontend deployment image
          sed -i '' "s|image:.*frontend.*|image: docker.io/frontend:$IMAGE_TAG|" frontend/deploy.yaml
        '''
      }
    }

    stage('Git Commit & Push Manifests') {
      steps {
        sh '''
          git config user.name "Jenkins"
          git config user.email "jenkins@example.com"
          
          git add backend/deploy.yaml frontend/deploy.yaml
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: update images to tag $IMAGE_TAG"
            git push origin HEAD:main
          else
            echo "No manifest changes to commit."
          fi

        '''
      }
    }
  }

  post {
    always {
      sh 'docker logout "$REGISTRY" || true'
    }
  }
}
