apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-service-api
  title: Payment Service API
  description: REST API for payment operations provided by the payment-service component.
  tags:
    - openapi
    - payments
spec:
  type: openapi
  lifecycle: production
  owner: group:default/digital-banking-platform
  system: dbb
  definition: |
    openapi: 3.0.0
    info:
      title: Payment Service API
      version: 1.0.0
      description: Small API for payment operations in digital banking.
    paths:
      /payments/{id}:
        get:
          summary: Get payment by ID
          operationId: getPayment
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
                format: uuid
          responses:
            "200":
              description: Payment found
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      amount:
                        type: number
                        format: double
                      status:
                        type: string
                        enum: [PENDING, COMPLETED, FAILED]
            "404":
              description: Payment not found
      /payments:
        post:
          summary: Create a payment
          operationId: createPayment
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required: [amount, currency]
                  properties:
                    amount:
                      type: number
                      format: double
                    currency:
                      type: string
                      example: USD
          responses:
            "201":
              description: Payment created
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      status:
                        type: string
                        example: PENDING
            "400":
              description: Invalid request
